version: '3.8'
services:
  jenkins:
    build: ./jenkins
    environment:
      NGROK_AUTH_TOKEN: ${NGROK_AUTH_TOKEN:-invalid}
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home: